[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
knot_escrow = "HeviXng9rwLz5sNDY6tixkYiW4kwxXRv5iFDo5xf3z4v"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "python3 -m pytest backend/tests -v"

[hooks]
